version: "3.1.0"
services:
  app:
    build:
      context: node
    container_name: app
    entrypoint: dockerize -wait tcp://db:3306 -timeout 30s docker-entrypoint.sh
    command: node index.js
    restart: always
    networks:
      - nginx-network
    tty: true
    depends_on:
      - db
  nginx:
    container_name: nginx
    build:
      context: nginx
    restart: always
    ports:
      - "8080:80"
    networks:
      - nginx-network
    depends_on:
      - app
  db:
    image: mysql:5.7
    platform: linux/x86_64
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - nginx-network
networks:
  nginx-network:
    driver: bridge
